---
name: Build

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ ubuntu, windows, macOS ]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: hecrj/setup-rust-action@v1.3.4
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      # same checks as with `cargo build`, but no binaries are generated at the end, saving some time.
      - run: cargo check

  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: hecrj/setup-rust-action@v1.3.4
        with:
          rust-version: stable
          components: rustfmt
      - run: cargo fmt -- --check
